# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "spin-wheel"
client_id = "d12ec54832adf75545dad65f28341ff2"
application_url = "https://air-ins-words-architect.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes"

[auth]
redirect_urls = [
  "https://air-ins-words-architect.trycloudflare.com/auth/callback",
  "https://air-ins-words-architect.trycloudflare.com/auth/shopify/callback",
  "https://air-ins-words-architect.trycloudflare.com/api/auth/callback",
  "https://air-ins-words-architect.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststore3222.myshopify.com"
